// ── Hardcoded Option B Suggestions ──\nconst YT_SUGGESTIONS = [\n  {
    videoId: '2oV1KwiTrdM',
    title: '99 Luftballons',
    artist: 'Nena',
    level: 'A2',
    lyrics: {
      original: [
        { line: "Hast du etwas Zeit für mich\nDann singe ich ein Lied für dich\nVon 99 Luftballons\nAuf ihrem Weg zum Horizont\nDenkst du vielleicht grad' an mich\nDann singe ich ein Lied für dich\nVon 99 Luftballons\nUnd dass sowas von sowas kommt\n\n99 Luftballons\nAuf ihrem Weg zum Horizont\nHielt man für Ufo's aus dem All\nDrum schickte ein General\n'ne Fliegerstaffel hinterher,\nAlarm zu geben, wenn's so wär'\nDabei war'n dort am Horizont\nNur 99 Luftballons.\n\n99 Düsenflieger\nJeder war ein großer Krieger\nHielten sich für Captain Kirk\nEs gab ein großes Feuerwerk\nDie Nachbarn haben nichts gerafft\nUnd fühlten sich gleich angemacht\nDabei schoss man am Horizont\nAuf 99 Luftballons\n\n99 Kriegsminister\nStreichholz und Benzinkanister\nHielten sich für schlaue Leute\nWitterten schon fette Beute\nRiefen Krieg und wollten Macht\nMann, wer hätte das gedacht\nDass es einmal soweit kommt\nWegen 99 Luftballons\nWegen 99 Luftballons\n99 Luftballons\n\n99 Jahre Krieg\nLießen keinen Platz für Sieger\nKriegsminister gibt's nicht mehr\nUnd auch keine Düsenflieger\nHeute zieh' ich meine Runden\nSeh' die Welt in Trümmern liegen\nHab' 'nen Luftballon gefunden\nDenk' an dich und lass' ihn fliegen", timestamp: 0 }
      ],
      german: [
        { line: "Hast du etwas Zeit für mich\nDann singe ich ein Lied für dich\nVon 99 Luftballons\nAuf ihrem Weg zum Horizont\nDenkst du vielleicht grad' an mich\nDann singe ich ein Lied für dich\nVon 99 Luftballons\nUnd dass sowas von sowas kommt\n\n99 Luftballons\nAuf ihrem Weg zum Horizont\nHielt man für Ufo's aus dem All\nDrum schickte ein General\n'ne Fliegerstaffel hinterher,\nAlarm zu geben, wenn's so wär'\nDabei war'n dort am Horizont\nNur 99 Luftballons.\n\n99 Düsenflieger\nJeder war ein großer Krieger\nHielten sich für Captain Kirk\nEs gab ein großes Feuerwerk\nDie Nachbarn haben nichts gerafft\nUnd fühlten sich gleich angemacht\nDabei schoss man am Horizont\nAuf 99 Luftballons\n\n99 Kriegsminister\nStreichholz und Benzinkanister\nHielten sich für schlaue Leute\nWitterten schon fette Beute\nRiefen Krieg und wollten Macht\nMann, wer hätte das gedacht\nDass es einmal soweit kommt\nWegen 99 Luftballons\nWegen 99 Luftballons\n99 Luftballons\n\n99 Jahre Krieg\nLießen keinen Platz für Sieger\nKriegsminister gibt's nicht mehr\nUnd auch keine Düsenflieger\nHeute zieh' ich meine Runden\nSeh' die Welt in Trümmern liegen\nHab' 'nen Luftballon gefunden\nDenk' an dich und lass' ihn fliegen", timestamp: 0 }
      ]
    },
    vocabulary: ["Luftballon","Horizont","singen","Krieger","fliegen"]
  }\n  {
    videoId: 'StZcUAPRRac',
    title: 'Sonne',
    artist: 'Rammstein',
    level: 'A1',
    lyrics: {
      original: [
        { line: "Eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, aus\n\nAlle warten auf das Licht\nFürchtet euch, fürchtet euch nicht\nDie Sonne scheint mir aus den Augen\nsie wird heut Nacht nicht untergehen\nund die Welt zählt laut bis zehn\n\nEins\nHier kommt die Sonne\nZwei\nHier kommt die Sonne\nDrei\nSie ist der hellste Stern von allen\nVier\nHier kommt die Sonne\n\nDie Sonne scheint mir aus den Händen\nkann verbrennen, kann euch blenden\nwenn sie aus den Fäusten bricht\nlegt sich heiss auf das Gesicht\nsie wird heut Nacht nicht untergehen\nund die Welt zählt laut bis zehn\n\nEins\nHier kommt die Sonne\nZwei\nHier kommt die Sonne\nDrei\nSie ist der hellste Stern von allen\nVier\nHier kommt die Sonne\nFünf\nHier kommt die Sonne\nSechs\nHier kommt die Sonne\nSieben\nSie ist der hellste Stern von allen\nAcht, neun\nHier kommt die Sonne\n\nDie Sonne scheint mir aus den Händen\nkann verbrennen, kann dich blenden\nwenn sie aus den Fäusten bricht\nlegt sich heiss auf dein Gesicht\nlegt sich schmerzend auf die Brust\ndas Gleichgewicht wird zum Verlust\nl ässt dich hart zu Boden gehen\nund die Welt zählt laut bis zehn\n\nEins\nHier kommt die Sonne\nZwei\nHier kommt die Sonne\nDrei\nSie ist der hellste Stern von allen\nVier\nUnd wird nie vom Himmel fallen\nFünf\nHier kommt die Sonne\nSechs\nHier kommt die Sonne\nSieben\nSie ist der hellste Stern von allen\nAcht , neun\nHier kommt die Sonne", timestamp: 0 }
      ],
      german: [
        { line: "Eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, aus\n\nAlle warten auf das Licht\nFürchtet euch, fürchtet euch nicht\nDie Sonne scheint mir aus den Augen\nsie wird heut Nacht nicht untergehen\nund die Welt zählt laut bis zehn\n\nEins\nHier kommt die Sonne\nZwei\nHier kommt die Sonne\nDrei\nSie ist der hellste Stern von allen\nVier\nHier kommt die Sonne\n\nDie Sonne scheint mir aus den Händen\nkann verbrennen, kann euch blenden\nwenn sie aus den Fäusten bricht\nlegt sich heiss auf das Gesicht\nsie wird heut Nacht nicht untergehen\nund die Welt zählt laut bis zehn\n\nEins\nHier kommt die Sonne\nZwei\nHier kommt die Sonne\nDrei\nSie ist der hellste Stern von allen\nVier\nHier kommt die Sonne\nFünf\nHier kommt die Sonne\nSechs\nHier kommt die Sonne\nSieben\nSie ist der hellste Stern von allen\nAcht, neun\nHier kommt die Sonne\n\nDie Sonne scheint mir aus den Händen\nkann verbrennen, kann dich blenden\nwenn sie aus den Fäusten bricht\nlegt sich heiss auf dein Gesicht\nlegt sich schmerzend auf die Brust\ndas Gleichgewicht wird zum Verlust\nl ässt dich hart zu Boden gehen\nund die Welt zählt laut bis zehn\n\nEins\nHier kommt die Sonne\nZwei\nHier kommt die Sonne\nDrei\nSie ist der hellste Stern von allen\nVier\nUnd wird nie vom Himmel fallen\nFünf\nHier kommt die Sonne\nSechs\nHier kommt die Sonne\nSieben\nSie ist der hellste Stern von allen\nAcht , neun\nHier kommt die Sonne", timestamp: 0 }
      ]
    },
    vocabulary: ["Sonne","Stern","hell","kommen","alle"]
  }\n  {
    videoId: 'v0y6oOBZ7Mk',
    title: 'Autobahn',
    artist: 'Kraftwerk',
    level: 'A1',
    lyrics: {
      original: [
        { line: "Wir fahr'n fahr'n fahr'n auf der Autobahn\n\nVor uns liegt ein weites Tal\nDie Sonne scheint mit Glitzerstrahl\n\nDie Fahrbahn ist ein graues Band\nWeisse Streifen, gruener Rand\n\nJetzt schalten wir ja das Radio an\nAus dem Lautsprecher klingt es dann:\nWir fah'rn auf der Autobahn...\n\n[English translation:]\n\nWe are driving on the Autobahn\n\nIn front of us is a wide valley\nThe sun is shining with glittering rays\n\nThe driving strip is a grey track\nWhite stripes, green edge\n\nWe are switching the radio on\nFrom the speaker it sounds:\n\nWe are driving on the Autobahn", timestamp: 0 }
      ],
      german: [
        { line: "Wir fahr'n fahr'n fahr'n auf der Autobahn\n\nVor uns liegt ein weites Tal\nDie Sonne scheint mit Glitzerstrahl\n\nDie Fahrbahn ist ein graues Band\nWeisse Streifen, gruener Rand\n\nJetzt schalten wir ja das Radio an\nAus dem Lautsprecher klingt es dann:\nWir fah'rn auf der Autobahn...\n\n[English translation:]\n\nWe are driving on the Autobahn\n\nIn front of us is a wide valley\nThe sun is shining with glittering rays\n\nThe driving strip is a grey track\nWhite stripes, green edge\n\nWe are switching the radio on\nFrom the speaker it sounds:\n\nWe are driving on the Autobahn", timestamp: 0 }
      ]
    },
    vocabulary: ["Autobahn","fahren","vor","Tal","Sonne"]
  }\n  {
    videoId: 'qdtLCfEcPL4',
    title: 'Alles Neu',
    artist: 'Peter Fox',
    level: 'B1',
    lyrics: {
      original: [
        { line: "Ich verbrenne mein Studio, schnupfe die Asche wie Koks.\nIch erschlag' meinen Goldfisch, vergrab ihn im Hof.\nIch jag meine Bude hoch, alles was ich hab lass ich los. (Eh...)\nMein altes Leben, schmeckt wie 'n labriger Toast.\nBrat mir ein Prachtsteak, Peter kocht jetzt feinstes Fleisch.\nBin das Update, Peter Fox 1.1\nIch will abshaken, feiern, doch mein Teich ist zu klein.\nMir wächst 'ne neue reihe Beißer wie bei 'nem weißen Hai. (Hou...)\n\nGewachst , gedoped , poliert, nagelneue Zähne.\nIch bin euphorisiert, und habe teure Pläne.\nIch kaufe mir Baumaschinen, Bagger und Walzen und Kräne.\nStürze mich auf Berlin , drück auf die Sirene.\nIch baue schöne Boxentürme, Bässe massieren eure Seele.\nIch bin die Abrissbirne für die d-d-d-deutsche Szene.\n\nHey, alles glänzt, so schön neu.\nHey, wenn's dir nicht gefällt, mach neu. (Hou...)\nDie Welt mit Staub bedeckt, doch ich will sehn wo's hingeht.\nSteig auf den Berg aus Dreck, weil oben frischer Wind weht.\nHey, alles glänzt, so schön neu.\n\nIch hab meine alten Sachen satt, und lass sie in 'nem Sack verrotten.\nMotte die Klamotten ein, und dann geh ich Nackt shoppen.\nIch bin komplett renoviert, Bräute haben was zu glotzen.\nKerngesund, durchtrainiert, Weltmeister im Schach und Boxen.\nNur noch konkret reden, gib mir ein ja oder nein.\nSchluss mit Larifari, ich lass all die alten Faxen sein.\nSollt' ich je wieder kiffen, hau ich mir 'ne Axt ins Bein.\nIch will nie mehr Lügen, ich will jeden Satz auch so meinen.\n\nMir platzt der Kopf, alles muss sich verändern.\nIch such den Knopf , treffe die mächtigen Männer.\nZwing das Land zum Glück, kaufe Banken und Sender.\nAlles spielt verrückt, zitternde Schafe und Lämmer.\nIch seh besser aus als Bono, und bin 'n Mann des Volkes.\nBereit die Welt zu retten ,auch wenn das vielleicht zu viel gewollt ist.\n\nHey, alles glänzt, so schön neu.\nHey, wenn's dir nicht gefällt, mach neu. (Hou...)\nHier ist die Luft verbraucht, das Atmen fällt mir schwer.\nBye Bye ich muss hier raus, die Wände kommen näher.\nDie Welt mit Staub bedeckt, doch ich will sehn wo's hingeht.\nSteig auf den Berg aus Dreck, weil oben frischer Wind weht.\nHey, alles glänzt, so schön neu", timestamp: 0 }
      ],
      german: [
        { line: "Ich verbrenne mein Studio, schnupfe die Asche wie Koks.\nIch erschlag' meinen Goldfisch, vergrab ihn im Hof.\nIch jag meine Bude hoch, alles was ich hab lass ich los. (Eh...)\nMein altes Leben, schmeckt wie 'n labriger Toast.\nBrat mir ein Prachtsteak, Peter kocht jetzt feinstes Fleisch.\nBin das Update, Peter Fox 1.1\nIch will abshaken, feiern, doch mein Teich ist zu klein.\nMir wächst 'ne neue reihe Beißer wie bei 'nem weißen Hai. (Hou...)\n\nGewachst , gedoped , poliert, nagelneue Zähne.\nIch bin euphorisiert, und habe teure Pläne.\nIch kaufe mir Baumaschinen, Bagger und Walzen und Kräne.\nStürze mich auf Berlin , drück auf die Sirene.\nIch baue schöne Boxentürme, Bässe massieren eure Seele.\nIch bin die Abrissbirne für die d-d-d-deutsche Szene.\n\nHey, alles glänzt, so schön neu.\nHey, wenn's dir nicht gefällt, mach neu. (Hou...)\nDie Welt mit Staub bedeckt, doch ich will sehn wo's hingeht.\nSteig auf den Berg aus Dreck, weil oben frischer Wind weht.\nHey, alles glänzt, so schön neu.\n\nIch hab meine alten Sachen satt, und lass sie in 'nem Sack verrotten.\nMotte die Klamotten ein, und dann geh ich Nackt shoppen.\nIch bin komplett renoviert, Bräute haben was zu glotzen.\nKerngesund, durchtrainiert, Weltmeister im Schach und Boxen.\nNur noch konkret reden, gib mir ein ja oder nein.\nSchluss mit Larifari, ich lass all die alten Faxen sein.\nSollt' ich je wieder kiffen, hau ich mir 'ne Axt ins Bein.\nIch will nie mehr Lügen, ich will jeden Satz auch so meinen.\n\nMir platzt der Kopf, alles muss sich verändern.\nIch such den Knopf , treffe die mächtigen Männer.\nZwing das Land zum Glück, kaufe Banken und Sender.\nAlles spielt verrückt, zitternde Schafe und Lämmer.\nIch seh besser aus als Bono, und bin 'n Mann des Volkes.\nBereit die Welt zu retten ,auch wenn das vielleicht zu viel gewollt ist.\n\nHey, alles glänzt, so schön neu.\nHey, wenn's dir nicht gefällt, mach neu. (Hou...)\nHier ist die Luft verbraucht, das Atmen fällt mir schwer.\nBye Bye ich muss hier raus, die Wände kommen näher.\nDie Welt mit Staub bedeckt, doch ich will sehn wo's hingeht.\nSteig auf den Berg aus Dreck, weil oben frischer Wind weht.\nHey, alles glänzt, so schön neu", timestamp: 0 }
      ]
    },
    vocabulary: ["verbrennen","Asche","erschlagen","vergraben","Leben"]
  }\n  {
    videoId: 'hK-mYC8QQ3A',
    title: 'Easy',
    artist: 'Cro',
    level: 'A2',
    lyrics: {
      original: [
        { line: "EASY, ea ea, mh mh\nEASY, ea ea, mh mh\n\nLeute sagen zu mir \"Cro das Genie\",\ndenn er flowt wieder wie\ndieser Hova\nund außerdem baut er die Beats\nes ist EASY, ea ea, mh mh\n\nUnd dieser Typ hier vergleicht sich mit Jay-Z\nund scheiß auf die Playsi\ndenn ich häng' ab mit Rockstars\ngenauso wie AC/D EASY, ea ea, mh mh\n\nIch chill im Bett mit ner Chic\ndie sieht aus\nwie die Sis' von Beyoncé,\ndoch eigentlich\ngeb ich n' Fick auf Frau'n\nwie EASY, ea ea, mh mh\n\nOk, das mit den Chics tut mir Leid,\nes war nicht so gemeint,\nkannst Du mir noch mal verzeihn' Ina,\nund Sie schreit\n\"Ich heiß\" EASY, ea ea, mh mh\n\nDoch wenn Sie plötzlich so kleines Ding zeigt,\ndu eiegntlich schon weißt\nder zweite Strich heißt\nes ist aus und vorbei bleib\nEASY, ea ea, mh mh\n\nUnd wenn Sie heiraten will\nund nach drei Tagen chilln\nschon Dein ganzes Haus und\nDeinen Leihwagen will\nersch EASY, ea ea, mh mh\n\nDoch das würd ich mich nicht traun'\nman das weiß ich genau,\ndenn davor hau ich ab\nund sing \"Run Away\"\nwie Kan-YEASY, ea ea, mh mh\n\nund dann lauf ich und lauf ich\nwohin ist noch offen\nam Besten nur weit, weit weg\nvielleicht Washington D EASY, ea ea, mh mh\n\nUnd diese Frau war verrückt\ndenn Sie hat mich erdrückt,\nSchreit \"Cro komm zurück\"\ndoch ich schlüpf grad in die\nAir EASY,und verl EASY,\nund mach den iPod an\nund alles was ich hör' ist\n\nSUNNY,ah,ah,ah\nich weiß schon Du heißt EASY\naber ist mir egal,\nich nenn dich lieber\nSUNNY,ah,ah,ah\nab jetzt wird alles EASY\ndenn du bist nicht mehr da\n\nSUNNY,ah,ah,ah\nich weiß schon Du heißt EASY\naber ist mir egal,\nich nenn dich lieber\nSUNNY,ah,ah,ah\nab jetzt wird alles EASY\ndenn du bist nicht mehr da\n\nEASY, ea ea, mh mh\nEASY, ea ea, mh mh", timestamp: 0 }
      ],
      german: [
        { line: "EASY, ea ea, mh mh\nEASY, ea ea, mh mh\n\nLeute sagen zu mir \"Cro das Genie\",\ndenn er flowt wieder wie\ndieser Hova\nund außerdem baut er die Beats\nes ist EASY, ea ea, mh mh\n\nUnd dieser Typ hier vergleicht sich mit Jay-Z\nund scheiß auf die Playsi\ndenn ich häng' ab mit Rockstars\ngenauso wie AC/D EASY, ea ea, mh mh\n\nIch chill im Bett mit ner Chic\ndie sieht aus\nwie die Sis' von Beyoncé,\ndoch eigentlich\ngeb ich n' Fick auf Frau'n\nwie EASY, ea ea, mh mh\n\nOk, das mit den Chics tut mir Leid,\nes war nicht so gemeint,\nkannst Du mir noch mal verzeihn' Ina,\nund Sie schreit\n\"Ich heiß\" EASY, ea ea, mh mh\n\nDoch wenn Sie plötzlich so kleines Ding zeigt,\ndu eiegntlich schon weißt\nder zweite Strich heißt\nes ist aus und vorbei bleib\nEASY, ea ea, mh mh\n\nUnd wenn Sie heiraten will\nund nach drei Tagen chilln\nschon Dein ganzes Haus und\nDeinen Leihwagen will\nersch EASY, ea ea, mh mh\n\nDoch das würd ich mich nicht traun'\nman das weiß ich genau,\ndenn davor hau ich ab\nund sing \"Run Away\"\nwie Kan-YEASY, ea ea, mh mh\n\nund dann lauf ich und lauf ich\nwohin ist noch offen\nam Besten nur weit, weit weg\nvielleicht Washington D EASY, ea ea, mh mh\n\nUnd diese Frau war verrückt\ndenn Sie hat mich erdrückt,\nSchreit \"Cro komm zurück\"\ndoch ich schlüpf grad in die\nAir EASY,und verl EASY,\nund mach den iPod an\nund alles was ich hör' ist\n\nSUNNY,ah,ah,ah\nich weiß schon Du heißt EASY\naber ist mir egal,\nich nenn dich lieber\nSUNNY,ah,ah,ah\nab jetzt wird alles EASY\ndenn du bist nicht mehr da\n\nSUNNY,ah,ah,ah\nich weiß schon Du heißt EASY\naber ist mir egal,\nich nenn dich lieber\nSUNNY,ah,ah,ah\nab jetzt wird alles EASY\ndenn du bist nicht mehr da\n\nEASY, ea ea, mh mh\nEASY, ea ea, mh mh", timestamp: 0 }
      ]
    },
    vocabulary: ["Leute","sagen","wieder","außerdem","bauen"]
  }\n];\n\nexport { YT_SUGGESTIONS };